changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Fixes
      labels:
        - bug
    - title: New Features
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"