scan_library:
  name: "Scan Library"
  description: "Scan a Tdarr Library"
  fields:
    library:
      name: Library
      description: "Library Name to refresh"
      required: true
      example: "Movies"
      selector:
        text:
    folderpath:
      name: Folder Path
      description: "Library Folder path e.g. /Movies (Have to include this for now)"
      example: "/Movies"
      required: true
      selector:
        text:
    mode:
      name: Scan Mode
      description: The type of scan to perform. Note that in the Tdarr UI 'Find New' will also remove missing files. It is included in the name here for clarity.
      required: true
      default: scanFindNew
      selector:
        select:
          translation_key: scan_mode
          options:
            - scanFindNew
            - scanFresh

