scan_library:
  name: "Scan Library"
  description: "Scan a Tdarr Library"
  fields:
    library:
      name: Library
      description: "Library Name to refresh"
      required: true
      example: "Movies"
      selector:
        text:
    mode:
      name: Scan Mode
      description: The type of scan to perform. Note that in the Tdarr UI 'Find New' will also remove missing files. It is included in the name here for clarity.
      required: true
      default: scanFindNew
      selector:
        select:
          translation_key: scan_mode
          options:
            - find_new
            - fresh
get_workers:
  name: Get Workers
  description: Gets the currently active workers for a given node